/*
==========================================================================
Dosya Adı: lang.js
==========================================================================
*/

var langs = {
    "vi": {
        "vi": "Tiếng Việt",
        "tr": "Türkçe",
        "en": "English",
        "ru": "Русский",
        "dosyalar_yukleniyor": "Đang tải dữ liệu...",
        "text_oyna": "Chơi Game",
        "text_nasil_oynanir": "Hướng Dẫn Chơi",
        "text_dil_secimi": "Chọn Ngôn Ngữ",
        "text_onay": "Duyệt Order",
        "text_red": "Từ Chối",
        "text_satin_al": "Mua Nguyên Liệu",
        "text_eller_bos": "Tay Đang Trống",
        "text_elinizde": "Đang Cầm",
        "hazirlama_alani": "Khu Chế Biến",
        "teslim_noktasi": "Nơi Giao Hàng",
        "yeni_siparisler": "Đơn Hàng Mới",
        "market": "Cửa Hàng Thực Phẩm",
        "et_dolabi": "Tủ Thịt Tươi", 
        "sebze_dolabi": "Tủ Rau Củ", 
        "ekmek_dolabi": "Tủ Bánh Mì", 
        "icecek_dolabi": "Tủ Nước Giải Khát", 
        "hazirlanmis_urunler_dolabi": "Món Đã Chế Biến",
        "kofte": "Chả Thịt",
        "pirzola": "Sườn Cừu",
        "sucuk": "Xúc Xích",
        "biftek": "Bít Tết Bo",
        "domates": "Cà Chùa",
        "sogan": "Hành Tây",
        "patates": "Khoai Tây",
        "peynir": "Phô Mai",
        "ekmek": "Bánh Mì Kẹp",
        "hamburger_ekmegi": "Vỏ Hamburger",
        "lavas": "Bánh Mì Cuộn",
        "ayran": "Sữa Chua Ayran",
        "limonata": "Nước Chanh",
        "kola": "Nước Ngọt Cola",
        "su": "Nước Lọc",
        "pismis_kofte": "Chả Thịt Nướng",
        "pismis_pirzola": "Sườn Cừu Nướng",
        "kozlenmis_domates": "Cà Chùa Nướng",
        "pismis_sucuk": "Xúc Xích Nướng",
        "pismis_biftek": "Bít Tết Nướng",
        "patates_kizartmasi": "Khoai Tây Chiên",
        "salata": "Salad Rau Củ",
        "sogan_halkasi": "Hành Tây Chiên",
        "peynirli_patates_kizartmasi": "Khoai Tây Phô Mai",
        "tost": "Bánh Mì Tost",
        "karisik_tabak": "Đĩa Thập Cẩm",
        "peynirli_salata": "Salad Phô Mai",
        "durum": "Thịt Cuộn Dürüm",
        "biftek_tabagi": "Đĩa Bít Tết Bo",
        "sucuk_ekmek": "Bánh Mì Xúc Xích",
        "hamburger": "Bánh Hamburger",
        "kofte_ekmek": "Bánh Mì Kẹp Chả",
        "pirzola_tabagi": "Đĩa Sườn Nướng",
        "text_nasil_oynanir_0": "Quán Ăn Của Linh là gì?",
        "text_nasil_oynanir_1": "Game là một trình mô phỏng quản lý nhà hàng / nấu ăn chạy trực tiếp trên trình duyệt. Bạn nhận order từ khách tại Quầy Thu Ngân (Kasa), nhận đơn và chế biến các món ăn tại Khu Chế Biến / Bếp Nướng. Khi hoàn thành đơn hàng, bạn nhận được tiền thưởng + lợi nhuận và số Sao đánh giá tùy theo tốc độ phục vụ!",
        "text_nasil_oynanir_2": "Cách di chuyển bếp trưởng Linh?",
        "text_nasil_oynanir_3": "Sử dụng các phím mũi tên (Arrow Keys) trên bàn phím để di chuyển nhân vật xung quanh quán ăn.",
        "text_nasil_oynanir_4": "Tại sao không thấy khách đặt đơn?",
        "text_nasil_oynanir_5": "Hãy kiểm tra nút trạng thái Quán ở góc trên bên phải xem đã bật sang màu XANH (ĐANG MỞ) chưa nhé! Quán mở thì khách mới tới đặt hàng.",
        "text_nasil_oynanir_6": "Làm sao để xem Đơn Hàng Mới?",
        "text_nasil_oynanir_7": "Di chuyển nhân vật chạm vào vùng 'Quầy Thu Ngân' (Kasa) để mở danh sách đơn hàng mới từ khách.",
        "text_nasil_oynanir_8": "Chấp nhận đơn hàng xong thì tìm ở đâu?",
        "text_nasil_oynanir_9": "Các đơn đã duyệt sẽ nằm ở vùng 'Nơi Giao Hàng' (Teslim Noktası). Chạm nhân vật vào đó để kiểm tra các món khách cần.",
        "text_nasil_oynanir_10": "Cách giao món cho khách?",
        "text_nasil_oynanir_11": "Cầm món ăn tương ứng trên tay, chạm nhân vật vào 'Nơi Giao Hàng' và nhấn vào ô món ăn của khách để trả hàng.",
        "text_nasil_oynanir_12": "Cách sử dụng Bếp Chiên và Bếp Nướng?",
        "text_nasil_oynanir_13": "Cầm nguyên liệu sống trên tay (mua từ Market), di chuyển tới Bếp và nhấn phím 'P' trên bàn phím để bắt đầu nướng/chiên. Khi chín bấm 'P' lần nữa để lấy món.",
        "text_nasil_oynanir_14": "Cách kết hợp chế biến món ăn?",
        "text_nasil_oynanir_15": "Đưa nhân vật tới 'Khu Chế Biến' (Hazırlama Alanı) để xem công thức, mua các nguyên liệu cần thiết, cầm từng thứ trên tay rồi chạm vào Khu Chế Biến để hoàn thành món phức hợp."
    },
    "tr": {
        "vi": "Tiếng Việt",
        "tr": "Türkçe",
        "en": "İngilizce",
        "ru": "Rusça",
        "dosyalar_yukleniyor": "Dosyalar Yükleniyor",
        "text_oyna": "Oyna",
        "text_nasil_oynanir": "Nasıl Oynanır?",
        "text_dil_secimi": "Dil Seçimi",
        "text_onay": "Onay",
        "text_red": "Red",
        "text_satin_al": "Satın Al",
        "text_eller_bos": "Eller Boşta",
        "text_elinizde": "Elinizde",
        "hazirlama_alani": "Hazırlama Alanı",
        "teslim_noktasi": "Teslim Noktası",
        "yeni_siparisler": "Yeni Siparişler",
        "market": "Market",
        "et_dolabi": "Et Dolabı", 
        "sebze_dolabi": "Sebze Dolabı", 
        "ekmek_dolabi": "Ekmek Dolabı", 
        "icecek_dolabi": "İçecek Dolabı", 
        "hazirlanmis_urunler_dolabi": "Hazırlanmış Ürünler",
        "kofte": "Köfte",
        "pirzola": "Pirzola",
        "sucuk": "Sucuk",
        "biftek": "Biftek",
        "domates": "Domates",
        "sogan": "Soğan",
        "patates": "Patates",
        "peynir": "Peynir",
        "ekmek": "Ekmek",
        "hamburger_ekmegi": "Hamburger E.",
        "lavas": "Lavaş",
        "ayran": "Ayran",
        "limonata": "Limonata",
        "kola": "Kola",
        "su": "Su",
        "pismis_kofte": "Pişmiş Köfte",
        "pismis_pirzola": "Pişmiş Pirzola",
        "kozlenmis_domates": "Közlenmiş Domates",
        "pismis_sucuk": "Pişmiş Sucuk",
        "pismis_biftek": "Pişmiş Biftek",
        "patates_kizartmasi": "Patates Kız.",
        "salata": "Salata",
        "sogan_halkasi": "Soğan Hal.",
        "peynirli_patates_kizartmasi": "Pey. Pat. Kız.",
        "tost": "Tost",
        "karisik_tabak": "Karışık Tab.",
        "peynirli_salata": "Peyn. Salata",
        "durum": "Dürüm",
        "biftek_tabagi": "Biftek Tab.",
        "sucuk_ekmek": "Sucuk Ekm.",
        "hamburger": "Hamburger",
        "kofte_ekmek": "Köfte Ekm.",
        "pirzola_tabagi": "Pirzola Tab.",
        "text_nasil_oynanir_0": "Babek's Steak House Nedir?",
        "text_nasil_oynanir_1": "Oyunumuz web tarayıcısında oynanabilen bir yemek yapma/restoran yönetme simulasyon oyunudur.",
        "text_nasil_oynanir_2": "Karakterimizi Nasıl Hareket Ettiririz?",
        "text_nasil_oynanir_3": "Karakterimizi klavyenin yön tuşlarıyla hareket ettirebilirsiniz.",
        "text_nasil_oynanir_4": "Neden Hiç Sipariş Gelmiyor?",
        "text_nasil_oynanir_5": "Eğer hiç sipariş gelmiyorsa öncelikle sağ üst köşeden dükkanı açtığınızdan emin olunuz.",
        "text_nasil_oynanir_6": "Yeni Siparişleri Nasıl Görebilirim?",
        "text_nasil_oynanir_7": "Yeni gelen siparişlerinizi görebilmek için karakterinizi 'Kasa' alanına temas ettiriniz.",
        "text_nasil_oynanir_8": "Siparişi Kabul Ettim Kayboldu?",
        "text_nasil_oynanir_9": "Kabul ettiğiniz siparişler 'Teslim Noktası' alanında görünmektedir.",
        "text_nasil_oynanir_10": "Siparişteki Ürünleri Nasıl Teslim Ederim?",
        "text_nasil_oynanir_11": "Teslim Noktası alanına temas edip ürünü teslim edebilirsiniz.",
        "text_nasil_oynanir_12": "Ocak ve Izgara Nasıl Kullanılır?",
        "text_nasil_oynanir_13": "Ürünü elimize alıp mobilyaya temas ettirip 'P' tuşuna basmalıyız.",
        "text_nasil_oynanir_14": "Ürün Nasıl Hazırlanır?",
        "text_nasil_oynanir_15": "Hazırlama Alanına temas ederek ürün hazırlayabilirsiniz."
    },
    "en": {
        "vi": "Vietnamese",
        "tr": "Turkish",
        "en": "English",
        "ru": "Russian",
        "dosyalar_yukleniyor" : "Files are loading",
        "text_oyna": "Play",
        "text_nasil_oynanir": "How to Play?",
        "text_dil_secimi": "Select Language",
        "text_onay": "Apply",
        "text_red": "Reject",
        "text_satin_al": "Buy",
        "text_eller_bos": "Hands Free",
        "text_elinizde": "In Your Hands",
        "hazirlama_alani": "Preparation Area",
        "teslim_noktasi": "Delivery Point",
        "yeni_siparisler": "New Orders",
        "market": "Market",
        "et_dolabi": "Meat Fridge",
        "sebze_dolabi": "Vegetable Fridge",
        "ekmek_dolabi": "Bread Cabinet",
        "icecek_dolabi": "Beverage Cooler",
        "hazirlanmis_urunler_dolabi": "Prepared Products",
        "kofte": "Meatballs",
        "pirzola": "Lamb Chops",
        "sucuk": "Sausage",
        "biftek": "Beef Steak",
        "domates": "Tomato",
        "sogan": "Onion",
        "patates": "Potato",
        "peynir": "Cheese",
        "ekmek": "Bread",
        "hamburger_ekmegi": "Hamburger Bun",
        "lavas": "Flatbread",
        "ayran": "Ayran",
        "limonata": "Lemonade",
        "kola": "Cola",
        "su": "Water",
        "pismis_kofte": "Cooked Meatballs",
        "pismis_pirzola": "Cooked Lamb Chops",
        "kozlenmis_domates": "Roasted Tomatoes",
        "pismis_sucuk": "Cooked Sausage",
        "pismis_biftek": "Cooked Beef Steak",
        "patates_kizartmasi": "Potato Wedges",
        "salata": "Salad",
        "sogan_halkasi": "Onion Rings",
        "peynirli_patates_kizartmasi": "Cheesy Potato Wedges",
        "tost": "Toast",
        "karisik_tabak": "Mixed Plate",
        "peynirli_salata": "Cheese Salad",
        "durum": "Wrap",
        "biftek_tabagi": "Beef Steak Plate",
        "sucuk_ekmek": "Sausage Sandwich",
        "hamburger": "Hamburger",
        "kofte_ekmek": "Meatball Sandwich",
        "pirzola_tabagi": "Lamb Chops Plate",
        "text_nasil_oynanir_0": "What is Cook With Linh?",
        "text_nasil_oynanir_1": "Our game is a cooking/restaurant management simulation game played in your browser.",
        "text_nasil_oynanir_2": "How Do We Move Our Character?",
        "text_nasil_oynanir_3": "You can move your character with arrow keys on your keyboard.",
        "text_nasil_oynanir_4": "Why Am I Not Getting Any Orders?",
        "text_nasil_oynanir_5": "Make sure you open the shop from top right corner button.",
        "text_nasil_oynanir_6": "How Can I See New Orders?",
        "text_nasil_oynanir_7": "Touch character to Cashier area.",
        "text_nasil_oynanir_8": "Accepted orders location?",
        "text_nasil_oynanir_9": "They appear in Delivery Point area.",
        "text_nasil_oynanir_10": "How Do I Deliver Products?",
        "text_nasil_oynanir_11": "Touch Delivery Point with item in hands.",
        "text_nasil_oynanir_12": "How Do I Use Stove/Grill?",
        "text_nasil_oynanir_13": "Hold raw item, touch stove/grill and press P key.",
        "text_nasil_oynanir_14": "How Do I Prepare Complex Products?",
        "text_nasil_oynanir_15": "Touch Preparation Area with ingredients."
    }
};

var word = langs["vi"];